import { StyleSheet } from "react-native";
import { background, logo, status, text } from "./colors";


export const loginStack = StyleSheet.create({
    backBtn: {
        position: 'absolute',
        top: -50,
        left: 0,
        borderRadius: 20,
        backgroundColor: background.secondary,
        justifyContent: 'center',
        alignItems: 'center',
    },
    otherBackBtn: {
        position: 'absolute',
        top: -50,
        left: 0,
        borderRadius: 20,
        backgroundColor: background.secondary,
        justifyContent: 'center',
        alignItems: 'center',
    },
    mainView: {
        width: '100%',
        height: "100%",
        backgroundColor: background.secondary,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 10,
        paddingVertical: 20,
        paddingTop: 50,
    },
    otherMainView: {
        width: '100%',
        height: "100%",
        backgroundColor: background.secondary,
        alignItems: 'center',
        justifyContent: 'flex-end',
        paddingHorizontal: 10,
        paddingVertical: 50,
    },
    formContainer: {
        width: '80%',
        minHeight: 500,
        maxHeight: 600,
        alignItems: 'center',
        justifyContent: 'center',
    },
    formContent: {
        width: '100%',
        height: "100%",
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
    },
    brand: {
        fontFamily: 'RooneySans-Bold',
        color: logo.orange,
        fontSize: 25,
    },
    formTitle: {
        marginTop: 10,
        fontFamily: 'Nunito-Bold',
        color: text.principal,
        fontSize: 35,
    },
    formTitleAdditional: {
        fontFamily: 'Nunito-Regular',
        color: text.attribute,
        fontSize: 22,
    },
    inputsContainer: {
        width: '100%',
        height: 'auto',
        flexDirection: 'column',
        alignItems: 'flex-start',
    },
    inputContainer: {
        width: '100%',
        height: 'auto',
        marginTop: 40,
    },
    inputLabel: {
        position: 'absolute',
        top: 8,
        fontSize: 18,
        color: text.placeholder,
        fontFamily: 'Nunito-Regular',
    },
    inputLabelActive: {
        position: 'absolute',
        // top: -20,
        fontSize: 16,
        color: logo.orange,
        fontFamily: 'Nunito-Bold',
    },
    inputLabelUnactive: {
        position: 'absolute',
        // top: -20,
        fontSize: 16,
        color: text.placeholder,
        fontFamily: 'Nunito-Bold',
    },
    formInput: {
        width: '100%',
        height: 40,
        borderBottomColor: text.placeholder,
        borderBottomWidth: 1,
        fontSize: 18,
        fontFamily: 'Nunito-Regular',
        color: text.principal,
    },
    formInputActive: {
        width: '100%',
        height: 40,
        borderBottomColor: logo.orange,
        borderBottomWidth: 1,
        fontSize: 18,
        fontFamily: 'Nunito-Regular',
        color: text.principal,
    },
    passwordContainer: {
        width: '100%',
        height: 'auto',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    formInputPassword: {
        width: '90.5%',
        height: 40,
        borderBottomColor: text.placeholder,
        borderBottomWidth: 1,
        fontSize: 18,
        fontFamily: 'Nunito-Regular',
        color: text.principal,
    },
    formInputPasswordActive: {
        width: '90%',
        height: 40,
        borderBottomColor: logo.orange,
        borderBottomWidth: 1,
        fontSize: 18,
        fontFamily: 'Nunito-Regular',
        color: text.principal,
    },
    otherInputsContainer: {
        width: '100%',
        height: '85%',
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        paddingBottom: 20,
    },
    countrySign: {
        fontFamily: 'Nunito-Regular',
        color: text.placeholder,
        fontSize: 20,
        paddingRight: 10,
    },
    countryInput: {
        width: '21%',
        height: 'auto',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        marginTop: 40,
        borderBottomColor: text.placeholder,
        borderBottomWidth: 1,
    },
    phoneInput: {
        width: '71%',
        height: 'auto',
        marginTop: 40,
        borderBottomColor: text.placeholder,
        borderBottomWidth: 1,
    },
    genderTitle: {
        fontFamily: 'Nunito-Regular',
        color: text.principal,
        fontSize: 20,
    },
    inputRadioContainer: {
        width: '100%',
        height: 'auto',
        marginTop: 10,
        marginLeft: -10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    radioBtnText: {
        fontFamily: 'Nunito-Regular',
        color: text.attribute,
        fontSize: 18,
        marginLeft: 5,
    },
    submitBtn: {
        width: '100%',
        height: 50,
        backgroundColor: logo.orange,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 50,
    },
    submitBtnDisabled: {
        width: '100%',
        height: 50,
        backgroundColor: text.placeholder,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 50,
    },
    submitBtnText: {
        fontFamily: 'Nunito-Bold',
        color: background.principal,
        fontSize: 20,
    },
    errorText: {
        fontSize: 10,
        color: status.error,
        position: 'absolute',
        top: 40,
    },
    lastMessageContainer: {
        width: '100%',
        height: 'auto',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 20,
    },
    lastMessageText: {
        fontFamily: 'Nunito-Bold',
        color: text.placeholder,
        fontSize: 15,
    },
    lastMessageBtn: {
        marginLeft: 5,
        fontFamily: 'Nunito-Bold',
        color: logo.orange,
        fontSize: 15,
    },
    linkText: {
        fontFamily: 'Nunito-Regular',
        color: text.principal,
        fontSize: 16,
        textDecorationLine: 'underline',
        textDecorationStyle: 'solid',
        textDecorationColor: logo.orange,
    }
});

